plugins:
  - rubocop-performance
  - rubocop-rspec

inherit_gem:
  rentacop:
    - rentacop.yml
    - rspec.yml

AllCops:
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - 'dev/**/*'

# Allow irregular filename here
Naming/FileName:
  Exclude:
    - 'examples/full-documented.rb'